export const ACTION_TYPE = {
    TASK: {
        ADD_TASK: "TL/TODOLIST/ADD_TASK",
        REMOVE_TASK: "TL/TODOLIST/REMOVE_TASK",
        CHANGE_TASK_STATUS: "TL/TODOLIST/CHANGE_TASK_STATUS",
        UPDATE_TASK_TITLE: "TL/TODOLIST/UPDATE_TASK_TITLE",
    },
    TODOLIST: {
        ADD_TODOLIST: "TL/TODOLIST/ADD_TODOLIST",
        REMOVE_TODOLIST: "TL/TODOLIST/REMOVE_TODOLIST",
        CHANGE_FILTER_VALUE: "TL/TODOLIST/CHANGE_FILTER_VALUE",
        UPDATE_TODO_TITLE: "TL/TODOLIST/UPDATE_TODO_TITLE",
    }
} as const

export const FILTER_VALUE = {
    ALL: "all",
    ACTIVE: "active",
    COMPLETED: "completed"
} as const